// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/auth/data_source/remote/auth_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:fitness_app/data/auth/api/auth_retrofit_client.dart' as _i7;
import 'package:fitness_app/data/auth/models/forget_password/request/forget_password_request_dto.dart'
    as _i10;
import 'package:fitness_app/data/auth/models/forget_password/response/forget_password_response_dto.dart'
    as _i3;
import 'package:fitness_app/data/auth/models/login/login_request_dto.dart'
    as _i13;
import 'package:fitness_app/data/auth/models/login/login_response_dto.dart'
    as _i6;
import 'package:fitness_app/data/auth/models/otp_verification/request/otp_verification_request_dto.dart'
    as _i11;
import 'package:fitness_app/data/auth/models/otp_verification/response/otp_verification_response_dto.dart'
    as _i4;
import 'package:fitness_app/data/auth/models/request/register_request_dto.dart'
    as _i9;
import 'package:fitness_app/data/auth/models/reset_password/request/reset_password_request_dto.dart'
    as _i12;
import 'package:fitness_app/data/auth/models/reset_password/response/reset_password_response_dto.dart'
    as _i5;
import 'package:fitness_app/data/auth/models/response/register_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpVerificationResponseDto_2 extends _i1.SmartFake
    implements _i4.OtpVerificationResponseDto {
  _FakeOtpVerificationResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponseDto_4 extends _i1.SmartFake
    implements _i6.LoginResponseDto {
  _FakeLoginResponseDto_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRetrofitClient extends _i1.Mock
    implements _i7.AuthRetrofitClient {
  MockAuthRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.RegisterResponseDto> register(
    _i9.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i8.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.RegisterResponseDto>);

  @override
  _i8.Future<_i3.ForgetPasswordResponseDto> forgetPassword(
    _i10.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i8.Future<_i3.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_1(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i3.ForgetPasswordResponseDto>);

  @override
  _i8.Future<_i4.OtpVerificationResponseDto> verifyOtp(
    _i11.OtpVerificationRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue: _i8.Future<_i4.OtpVerificationResponseDto>.value(
              _FakeOtpVerificationResponseDto_2(
                this,
                Invocation.method(#verifyOtp, [request]),
              ),
            ),
          )
          as _i8.Future<_i4.OtpVerificationResponseDto>);

  @override
  _i8.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i12.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i8.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.ResetPasswordResponseDto>);

  @override
  _i8.Future<_i6.LoginResponseDto> login(_i13.LoginRequestDto? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i6.LoginResponseDto>.value(
              _FakeLoginResponseDto_4(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.LoginResponseDto>);
}
