// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/domain/workouts/use_case/get_all_muscles_by_muscle_group_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/utils/datasource_excution/api_result.dart'
    as _i4;
import 'package:fitness_app/domain/workouts/entity/msucles_group_entity.dart'
    as _i5;
import 'package:fitness_app/domain/workouts/entity/muscles_entity.dart' as _i7;
import 'package:fitness_app/domain/workouts/repo/workouts_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutsRepo extends _i1.Mock implements _i2.WorkoutsRepo {
  MockWorkoutsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.MusclesGroupEntity>>> getAllMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleGroups, []),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.MusclesGroupEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.MusclesGroupEntity>>>(
                    this,
                    Invocation.method(#getAllMuscleGroups, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.MusclesGroupEntity>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.MusclesEntity>>> getAllMusclesByMuscleGroup(
    String? muscleGroupId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMusclesByMuscleGroup, [muscleGroupId]),
            returnValue: _i3.Future<_i4.Result<List<_i7.MusclesEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.MusclesEntity>>>(
                this,
                Invocation.method(#getAllMusclesByMuscleGroup, [muscleGroupId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.MusclesEntity>>>);
}
