// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/auth/repo_impl/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:fitness_app/core/utils/datasource_excution/api_manager.dart'
    as _i13;
import 'package:fitness_app/core/utils/datasource_excution/api_result.dart'
    as _i14;
import 'package:fitness_app/data/auth/data_source/local/auth_local_data_source_impl.dart'
    as _i12;
import 'package:fitness_app/data/auth/data_source/remote/auth_remote_data_source_impl.dart'
    as _i6;
import 'package:fitness_app/data/auth/models/forget_password/request/forget_password_request_dto.dart'
    as _i9;
import 'package:fitness_app/data/auth/models/forget_password/response/forget_password_response_dto.dart'
    as _i3;
import 'package:fitness_app/data/auth/models/otp_verification/request/otp_verification_request_dto.dart'
    as _i10;
import 'package:fitness_app/data/auth/models/otp_verification/response/otp_verification_response_dto.dart'
    as _i4;
import 'package:fitness_app/data/auth/models/request/register_request_dto.dart'
    as _i8;
import 'package:fitness_app/data/auth/models/reset_password/request/reset_password_request_dto.dart'
    as _i11;
import 'package:fitness_app/data/auth/models/reset_password/response/reset_password_response_dto.dart'
    as _i5;
import 'package:fitness_app/data/auth/models/response/register_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRegisterResponseDto_0 extends _i1.SmartFake
    implements _i2.RegisterResponseDto {
  _FakeRegisterResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_1 extends _i1.SmartFake
    implements _i3.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpVerificationResponseDto_2 extends _i1.SmartFake
    implements _i4.OtpVerificationResponseDto {
  _FakeOtpVerificationResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponseDto_3 extends _i1.SmartFake
    implements _i5.ResetPasswordResponseDto {
  _FakeResetPasswordResponseDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceImpl extends _i1.Mock
    implements _i6.AuthRemoteDataSourceImpl {
  MockAuthRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.RegisterResponseDto> register(
    _i8.RegisterRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request]),
            returnValue: _i7.Future<_i2.RegisterResponseDto>.value(
              _FakeRegisterResponseDto_0(
                this,
                Invocation.method(#register, [request]),
              ),
            ),
          )
          as _i7.Future<_i2.RegisterResponseDto>);

  @override
  _i7.Future<_i3.ForgetPasswordResponseDto> forgetPassword(
    _i9.ForgetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i7.Future<_i3.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_1(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i7.Future<_i3.ForgetPasswordResponseDto>);

  @override
  _i7.Future<_i4.OtpVerificationResponseDto> verifyOtp(
    _i10.OtpVerificationRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [request]),
            returnValue: _i7.Future<_i4.OtpVerificationResponseDto>.value(
              _FakeOtpVerificationResponseDto_2(
                this,
                Invocation.method(#verifyOtp, [request]),
              ),
            ),
          )
          as _i7.Future<_i4.OtpVerificationResponseDto>);

  @override
  _i7.Future<_i5.ResetPasswordResponseDto> resetPassword(
    _i11.ResetPasswordRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i7.Future<_i5.ResetPasswordResponseDto>.value(
              _FakeResetPasswordResponseDto_3(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i7.Future<_i5.ResetPasswordResponseDto>);
}

/// A class which mocks [AuthLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceImpl extends _i1.Mock
    implements _i12.AuthLocalDataSourceImpl {
  MockAuthLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> deleteToken(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, [key]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getToken(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [key]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> saveToken(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [key, value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ApiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiManager extends _i1.Mock implements _i13.ApiManager {
  MockApiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i14.Result<T>> execute<T>(_i7.Future<T> Function()? apiCall) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [apiCall]),
            returnValue: _i7.Future<_i14.Result<T>>.value(
              _i15.dummyValue<_i14.Result<T>>(
                this,
                Invocation.method(#execute, [apiCall]),
              ),
            ),
          )
          as _i7.Future<_i14.Result<T>>);
}
