// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/features/meals/presentation/view_model/meals_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fitness_app/core/utils/datasource_excution/api_result.dart'
    as _i4;
import 'package:fitness_app/domain/meals/entity/category_entity.dart' as _i5;
import 'package:fitness_app/domain/meals/entity/meal_entity.dart' as _i8;
import 'package:fitness_app/domain/meals/use_case/get_categories_use_case.dart'
    as _i2;
import 'package:fitness_app/domain/meals/use_case/get_meals_by_category_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i2.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.CategoryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.CategoryEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.CategoryEntity>>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.CategoryEntity>>>);
}

/// A class which mocks [GetMealsByCategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMealsByCategoryUseCase extends _i1.Mock
    implements _i7.GetMealsByCategoryUseCase {
  MockGetMealsByCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.MealEntity>>> call({
    required String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#category: category}),
            returnValue: _i3.Future<_i4.Result<List<_i8.MealEntity>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.MealEntity>>>(
                this,
                Invocation.method(#call, [], {#category: category}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.MealEntity>>>);
}
