// Mocks generated by Mockito 5.4.5 from annotations
// in fitness_app/test/data/workouts/data_source/remote/workouts_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fitness_app/data/workouts/api/workouts_retrofit_client.dart'
    as _i4;
import 'package:fitness_app/data/workouts/models/muscles_response_dto.dart'
    as _i3;
import 'package:fitness_app/data/workouts/models/workouts_response_dto.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutsResponseDto_0 extends _i1.SmartFake
    implements _i2.WorkoutsResponseDto {
  _FakeWorkoutsResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMusclesResponseDto_1 extends _i1.SmartFake
    implements _i3.MusclesResponseDto {
  _FakeMusclesResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkoutsRetrofitClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutsRetrofitClient extends _i1.Mock
    implements _i4.WorkoutsRetrofitClient {
  MockWorkoutsRetrofitClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WorkoutsResponseDto> getAllMuscleGroups() =>
      (super.noSuchMethod(
            Invocation.method(#getAllMuscleGroups, []),
            returnValue: _i5.Future<_i2.WorkoutsResponseDto>.value(
              _FakeWorkoutsResponseDto_0(
                this,
                Invocation.method(#getAllMuscleGroups, []),
              ),
            ),
          )
          as _i5.Future<_i2.WorkoutsResponseDto>);

  @override
  _i5.Future<_i3.MusclesResponseDto> getAllMusclesByMuscleGroup(
    String? muscleGroupId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllMusclesByMuscleGroup, [muscleGroupId]),
            returnValue: _i5.Future<_i3.MusclesResponseDto>.value(
              _FakeMusclesResponseDto_1(
                this,
                Invocation.method(#getAllMusclesByMuscleGroup, [muscleGroupId]),
              ),
            ),
          )
          as _i5.Future<_i3.MusclesResponseDto>);
}
