class AppIcons {
  AppIcons._();

  static const String fitnessOne = 'assets/svgs/fitness_1.svg';
  static const String fitnessTwo = 'assets/svgs/fitness_2.svg';
  static const String fitnessThree = 'assets/svgs/fitness_3.svg';
  static const String fitnessFour = 'assets/svgs/fitness_4.svg';
  static const String fitnessFive = 'assets/svgs/fitness_5.svg';
  static const String fitnessSix = 'assets/svgs/fitness_6.svg';
  static const String fitnessSeven = 'assets/svgs/fitness_7.svg';
  static const String fitnessEight = 'assets/svgs/fitness_8.svg';
  static const String fitnessNine = 'assets/svgs/fitness_9.svg';
  static const String fitnessTen = 'assets/svgs/fitness_10.svg';
  static const String fitnessEleven = 'assets/svgs/fitness_11.svg';
  static const String fitnessTwelve = 'assets/svgs/fitness_12.svg';
  static const String fitnessThirteen = 'assets/svgs/fitness_13.svg';
  static const String fitnessFourteen = 'assets/svgs/fitness_14.svg';
  static const String fitnessFifteen = 'assets/svgs/fitness_15.svg';
  static const String fitnessSixteen = 'assets/svgs/fitness_16.svg';
  static const String fitnessSeventeen = 'assets/svgs/fitness_17.svg';
  static const String fitnessEighteen = 'assets/svgs/fitness_18.svg';
  static const String fitnessNineteen = 'assets/svgs/fitness_19.svg';
  static const String fitnessTwenty = 'assets/svgs/fitness_20.svg';
  static const String fitnessTwentyOne = 'assets/svgs/fitness_21.svg';
  static const String fitnessTwentyTwo = 'assets/svgs/fitness_22.svg';
  static const String fitnessTwentyThree = 'assets/svgs/fitness_23.svg';
  static const String fitnessTwentyFour = 'assets/svgs/fitness_24.svg';
  static const String fitnessTwentyFive = 'assets/svgs/fitness_25.svg';
  static const String fitnessTwentySix = 'assets/svgs/fitness_26.svg';
  static const String fitnessTwentySeven = 'assets/svgs/fitness_27.svg';
  static const String fitnessTwentyEight = 'assets/svgs/fitness_28.svg';
  static const String fitnessTwentyNine = 'assets/svgs/fitness_29.svg';
  static const String fitnessThirty = 'assets/svgs/fitness_30.svg';
  static const String fitnessThirtyOne = 'assets/svgs/fitness_31.svg';
  static const String fitnessThirtyTwo = 'assets/svgs/fitness_32.svg';
  static const String fitnessThirtyThree = 'assets/svgs/fitness_33.svg';
  static const String fitnessThirtyFour = 'assets/svgs/fitness_34.svg';
  static const String homeIcon = 'assets/svgs/home_icon.svg';
  static const String profileIcon = 'assets/svgs/profile_icon.svg';
  static const String chatIcon = 'assets/svgs/chat_icon.svg';
  static const String workoutIcon = 'assets/svgs/workout_icon.svg';
  static const String mailLogo = 'assets/svgs/mail.svg';
  static const String lockLogo = 'assets/svgs/lock.svg';
  static const String eyeLogo = 'assets/svgs/eye.svg';
  static const String userIcon = 'assets/svgs/user.svg';
}
