name: Validate Branch Name

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name: $BRANCH_NAME"

          # Allowed types
          PREFIXES="feature|fix|hotfix|refactor|bugfix|release|docs|perf|test|chore"

          # Allowed special branch names
          ALLOWED_BRANCHES="main|development"

          # Check if branch is explicitly allowed
          if [[ "$BRANCH_NAME" =~ ^($ALLOWED_BRANCHES)$ ]]; then
            echo "✅ Allowed branch name: $BRANCH_NAME"
            exit 0
          fi

          # Regex pattern: type/fit-123-task-name
          PATTERN="^($PREFIXES)/fit-[0-9]+(-[a-z0-9\-]+)*$"

          # Validate branch name
          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch names must follow the pattern: type/fit-123-task-name"
            echo "Examples: feature/fit-456-login-api, fix/fit-789-crash-issue"
            echo "Allowed types: $PREFIXES"
            echo "Allowed special branches: main, development"
            exit 1
          fi

          echo "✅ Branch name is valid!"
